# Plik konfiguracyjny GitHub Actions - definiuje workflow do automatycznego testowania API za pomocą Newmana. 
# Workflow jest uruchamiany przy każdym pushu do gałęzi main oraz i przy każdym pull request.
# W sekcji jobs jest zadanie "api-tests", wykonywane na najnowszym systemie Ubuntu.
# Sekcja steps - kroki do checkoutu kodu, ustawienia Node.js, instalacji zależności, uruchomienia testów pozytywnych i negatywnych oraz uploadu raportów jako artefaktów.
name: API Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci

      - name: Run Positive Tests
        run: npx newman run postman/collection.json \
              -e postman/environments/ci.json \
              -d data/positive-cities.json \
              -r html \
              --reporter-html-export reports/report-positive.html

      - name: Run Negative Tests
        run: npx newman run postman/collection.json \
              -e postman/environments/ci.json \
              -d data/negative-cities.json \
              -r html \
              --reporter-html-export reports/report-negative.html

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: reports/